config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reviews, except: [:index, :show]
  resources :activities
  resources :neighborhoods, only: [:index, :show]
  resources :pictures, except: [:index, :show]
  resources :friendships, only: [:create, :destroy]
  root 'neighborhoods#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews#, dependent: :destroy
  has_many :activities, through: :reviews
  has_many :friendships, foreign_key: :user_id, class_name: "Friendship"#, dependent: :destroy
  has_many :followees, through: :friendships

  has_many :on_friendship_list, foreign_key: :followee_id, class_name: "Friendship"
  has_many :followers, through: :on_friendship_list

  has_secure_password

  validates :name, uniqueness: true

 

  def num_of_reviews
    self.reviews.length
  end

  def average_rating
    average = self.reviews.inject(0.0) { |sum, r| sum += r.rating}/self.num_of_reviews
    average.round(1)
  end

  def most_reviewed_hood
    hood_array = self.reviews.map do |r|
      r.activity.neighborhood
    end
    hood_hash = hood_array.inject(Hash.new(0)) { |h, v| h[v] += 1; h }
    the_hood = hood_array.max_by { |v| hood_hash[v]}
    if the_hood
      the_hood.name
    end
  end

  def all_followees_reviews
    self.followees.map do |f|
      f.reviews
    end.flatten
  end

  def top_ten_followee_reviews
    self.all_followees_reviews.max_by(10) { |f| f.updated_at}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :find_user, only: [:show, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      log_in @user
      redirect_to neighborhoods_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  # def destroy
  #   @user.destroy
  #   redirect_to login_path
  # end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
<%= f.label :name, "Username" %><br>
<%= f.text_field :name %><br>

<%= f.label :password %><br>
<%= f.password_field :password %><br>

<%= f.submit :class=>"btn btn-secondary"%>
<% end %>

app/views/users/new.erb
<div class="prime-sign-up">

<% provide(:title, "Sign Up") %>
<h1>Create a User</h1>

<%= render "form" %>
</div>

app/views/users/show.erb
<div class="prime-user">

<div class="two-fifths">

<h1><%= @user.name %></h1>

<% if @user != current_user && !current_user.followees.include?(@user) %>
  <%= button_to "follow", friendships_path, {params: {:followee_id => @user.id, :user_id => current_user.id}}  %>
<% elsif current_user.followees.include?(@user) && @user != current_user %>
  <%= button_to "following", friendship_path, {method: :delete, params: {followee_id: @user.id}} %>
<% end %>

<%# number of reviews %>
<p>   Number of reviews:
<%= @user.num_of_reviews %><br>
<%# average rating for reviews %>
   Average rating for reviews:
<%= @user.average_rating %>/5<br>
<%# most reviews in a neighborhood %>
   Favorite Neighborhood:
<%= @user.most_reviewed_hood %>
</p>

<% if current_user.followees.include?(@user) || current_user == @user %>

<% @user.reviews.each do |review| %>
<div class="card">
  <div class="card-header">
    <%= link_to review.activity.name, activity_path(review.activity) %>
  </div>
  <div class="card-body full-width">
    <p class="card-text user-r-info">
      <small>Rating: <%= review.rating %>/5</small><br>
      <%= review.description %>
    </p>
    <span id="review-opts">
      <%= button_to "Edit Review", edit_review_path(review), {method: :get} if current_user == review.user %>
      <%= button_to "Delete Review", review_path, {method: :delete, params: {user_show: true, review_id: review.id}} if current_user == review.user %>
    </span>
  </div>
</div>
  <% end %>


</div>

<div class="one-fifth">

<% if current_user == @user  %>
<h4>Yo Friends</h4>
<p class="face">
  <% @user.followees.each do |f| %>
  <%= link_to f.name, user_path(f) %><br>
  <% end %>
</p>

<h4>Recent Friend Reviews</h4>
<% @user.top_ten_followee_reviews.each do |fr| %>
<p><%= link_to fr.user.name, user_path(fr.user) %><br>
  <%= link_to fr.activity.name, activity_path(fr.activity) %>
  Rating:
<%= fr.rating %>/5
<%= fr.description %></p>
<% end %>

</div>

<%# <% if current_user == @user  %>
<%# button_to "delete user", user_path(@user), {method: :delete} %>
<%# end %>
<% end %>
<% end %>

</div>