config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reviews, except: [:index, :show]
  resources :activities
  resources :neighborhoods, only: [:index, :show]
  resources :pictures, except: [:index, :show]
  resources :friendships, only: [:create, :destroy]
  root 'neighborhoods#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  has_many :activities


  # have a picture for each neighborhood from the neighborhood's reviews

  def hood_pic
    foo = []
    self.activities.each do |activity|
      activity.reviews.each do |review|
        if review.picture
          foo << review.picture
        end
      end
    end
    foo.sample.img_url
  end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

  def index
    @neighborhoods = Neighborhood.all
  end

  def show
    session[:neighborhood_id] = nil
    @neighborhood = Neighborhood.find(params[:id])

    @CATEGORY = ["restaurant", "retail", "monument", "museum", "park", "nightclub", "bar"]
    @SETTING = ["indoor", "outdoor", "both"]
    params[:search] ? filter = params[:search].slice(:category, :setting) : filter = {}
    @activities = Activity.filter_by_neighborhood(@neighborhood.id, filter)
  end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/edit.erb
<h1>Neighborhood Edit Form</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @neighborhood do |f| %>
<%= f.label :name %><br>
<%= f.text_area :name %><br>
<%= f.label :description %><br>
<%= f.text_area :description %><br>
<%= f.submit :class=>"btn btn-secondary"%>
<% end %>

app/views/neighborhoods/index.erb
<div class="neighborhoods-container">

  <div class="hood-header">
    <h1>Hood</h1>
  </div>

  <div class="neighborhood-body-container">
    <% @neighborhoods.each do |neighborhood| %>

    <div class="card" style="width: 26rem;">
      <img class="card-img-top" src="<%= neighborhood.hood_pic %>" alt="<%=neighborhood.name%>">
      <div class="hood-index">
        <div class="card-text"><h3><%= link_to neighborhood.name, neighborhood_path(neighborhood) %></h3></div>
      </div>
    </div>


    <%# <img class="hood-pic" src=<%= neighborhood.hood_pic %>

    <% end %>
  </div>

</div>

app/views/neighborhoods/show.erb
<div class="prime">

<div class="left">
  <h1 class="hood-show-header"><%= @neighborhood.name %></h1>
  <p><%= @neighborhood.description %></p>
  <%= form_tag neighborhood_path(@neighborhood), method: :get do %>
  <%= label_tag :category %>
  <%= collection_select :search, :category, @CATEGORY, :to_s, :capitalize, prompt: true  %><br>

  <%= label_tag :setting %>
  <%= collection_select :search, :setting, @SETTING, :to_s, :capitalize, prompt: true  %><br>

  <%= submit_tag "Filter" %>
  <% end %>

  <p><%= button_to "Add activity", new_activity_path(@neighborhood.id), method: :get %></p><br>
</div>

<div class="right">
  <% @activities.each do |activity| %>
  <div class="card act-each">
  <div class="card-body">
    <% if activity.reviews && activity.reviews.any? { |review| !review.picture.img_url.empty? } %>
    <h5 class="card-title">
      <%= link_to image_tag(activity.reviews.find {|review| !review.picture.img_url.empty? }.picture.img_url), activity_path(activity) %>
    </h5>
    <% end %>
    <p class="card-text hood-act-pic" >
      <%= link_to activity.name, activity_path(activity) %><br>
      <%= activity.reviews.length %> <%= "Review".pluralize(activity.reviews.length) %><br>
      <%= activity.category.capitalize %>
    </p>

  </div>
</div>
  <% end %>

</div>

</div>

  <!-- <img src=<%= @neighborhood.hood_pic %>> -->