config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reviews, except: [:index, :show]
  resources :activities
  resources :neighborhoods, only: [:index, :show]
  resources :pictures, except: [:index, :show]
  resources :friendships, only: [:create, :destroy]
  root 'neighborhoods#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/activity.rb
require 'open-uri'
class Activity < ApplicationRecord
  has_many :reviews
  belongs_to :neighborhood
  has_one :time_of_day

  validates :name, presence: true
  validates :category, presence: true
  validates :setting, presence: true
  validate :formatted_correctly_url
  # validate :correct_uri

  scope :category, ->(category) {where category: category}
  scope :setting, ->(setting) { where setting: setting }



  def formatted_correctly_url
    if !(!self.url_link.starts_with?("http://") || !self.url_link.starts_with?("https://"))
      errors.add(:url_link, "needs to start with http:// to be a valid link")
    end
  end

  def tod
    self.time_of_day.attributes.select do |k, v|
      v == true
    end.keys
  end

  def average_rating
    self.reviews.inject(0.0) do |sum, review|
      sum += review.rating
    end / self.reviews.length
  end

  def tod_output
    self.tod.map do |td|
      if td == "late_night"
        "Late Night"
      else
        td.capitalize
      end
    end.join(", ")
  end

  def self.filter_by_neighborhood(neighborhood_id, filter_queries)
    response = self.where("neighborhood_id = ?", neighborhood_id)
    filter_queries.each do |key, value|
      response = response.public_send(key, value) if value.present?
    end
    response
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :find_activity, only: [:show, :edit, :update]

  def index
    @all_activities = Activity.all
  end

  def show
    session[:activity_id] = nil
  end

  def new

    session[:neighborhood_id] ||= params[:format]
    @activity = Activity.new
    @neighborhood = Neighborhood.find(session[:neighborhood_id].to_i)
    @CATEGORY = ["restaurant", "retail", "monument", "museum", "park", "nightclub", "bar"]
    @SETTING = ["indoor", "outdoor", "both"]
    @time_of_day = TimeOfDay.new
  end

  def create
    @activity = Activity.create(activity_params)
    @time_of_day = TimeOfDay.new(params.require(:time_of_day).permit(:morning, :afternoon, :evening, :late_night))
    @time_of_day.save
    @time_of_day.update(activity_id: @activity.id)
    if @activity.valid? && @time_of_day.valid?
      session[:neighborhood_id] = nil
      redirect_to @activity
    else
      flash[:a_errors] = @activity.errors.full_messages
      flash[:tod_errors] = @time_of_day.errors.full_messages
      redirect_to new_activity_path
    end
  end

  def edit

    @CATEGORY = ["restaurant", "retail", "monument", "museum", "park", "nightclub", "bar"]
    @SETTING = ["indoor", "outdoor", "both"]
    @time_of_day = TimeOfDay.new
  end

  def update
    # byebug
    @activity.update(activity_params)
    if @activity.valid?
      redirect_to @activity
    else
      flash[:a_errors] = @activity.errors.full_messages
      flash[:tod_errors] = @time_of_day.errors.full_messages
      redirect_to edit_activity_path
    end
  end

  private

  def find_activity
    @activity = Activity.find(params[:id])
  end


  def activity_params
    params.require(:activity).permit(:name, :category, :setting, :tod, :neighborhood_id, :url_link)
  end

  def slugify(name)
    name.downcase.strip.gsub(' ', '+').gsub(/[^\w+]/, '')
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.erb
<% if flash[:a_errors] || flash[:tod_errors]%>
  <% flash[:a_errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
  <% flash[:tod_errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @activity do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :category %><br>
<%= f.collection_select :category, @CATEGORY, :to_s, :capitalize, prompt: true  %><br>

<%= fields_for @time_of_day do |f|  %>
  <p>Choose all that apply</p>
<%= f.label :morning %>
<%= f.check_box :morning %>

<%= f.label :afternoon %>
<%= f.check_box :afternoon %>

<%= f.label :evening %>
<%= f.check_box :evening %>

<%= f.label :late_night %>
<%= f.check_box :late_night %><br>
<% end %>

<%= f.label :setting %><br>
<%= f.collection_select :setting, @SETTING, :to_s, :capitalize, prompt: true  %><br>

<%= f.hidden_field :neighborhood_id, :value => session[:neighborhood_id] %>

<%= f.label :url_link %><br>
<%= f.text_field :url_link %><br>
<%= f.submit :class=>"btn btn-secondary" %>
<% end %>

app/views/activities/edit.erb
<div class="form-container">

<h1>Edit Activity</h1>

<%= render "form" %>

</div>

app/views/activities/new.erb
<div class="form-container">

<h1>New Activity</h1>
<h2><%= @neighborhood.name %></h2>
<%= render "form" %>

</div>

app/views/activities/show.erb
<div class="prime_activity">
  <%# image_tag "#{@activity.neighborhood.name}.jpg" %>
  <div class="top">
    <h1> <%= @activity.name %> </h1>

    <h3> <%= @activity.neighborhood.name %> </h3>

    <p>Category: <%= @activity.category.capitalize %></p>

    <p>This is an <%= @activity.setting %> activity</p>


    <p>Best time to go: <%= @activity.tod_output %></p>

    <p>Average Ratings: <%= @activity.reviews.length > 0 ? @activity.average_rating.round(1) : "-" %> / 5 (out of <%= @activity.reviews.length %> <%= @activity.reviews.length == 1 ? "review" : "reviews" %>)</p>



    <% if @activity.url_link %>
    <p><%= link_to "visit their website", @activity.url_link %></p>
    <% end %>

    <p><%= button_to "Review This", new_review_path(@activity.id), method: :get %></p>
    <h2>Reviews</h2>
  </div>

<div class="reviews">


  <% @activity.reviews.each do |review| %>
  <!-- <div class="card-header">
    Featured
  </div> -->
  <div class="card act-revs">
    <div class="act-info">
      <div class="card-title review-pic">
        <% if !review.picture.img_url.empty? %>
        <img src= <%= review.picture.img_url %>>
        <% end %>
      </div>
      <div class="info-container">
        <p class="card-text act-text">
          <%= review.description %><br>
          Rating: <%= review.rating %>/5 <br>
          - <%= link_to review.user.name, user_path(review.user) %>
        </p>
        <p class="float-right d-tag">
          <%= button_to "Delete Review", review_path, {method: :delete, params: {review_id: review.id}} if current_user == review.user %>
        </p>
        <small class="">
          <% if !review.picture.img_url.empty? %>
          Caption:
          <%= review.picture.caption %><br>
          <% end %>
        </small>
      </div>
    </div>
  </div>
  <% end %>
  <br>



</div>

</div>